# This workflow will build and publish your package to PyPI when you create a new release
# For more information see: https://github.com/pypa/gh-action-pypi-publish

name: Publish Python 🐍 package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build tool
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
